// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.5
// source: pb/shellService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId         string `protobuf:"bytes,1,opt,name=AgentId,proto3" json:"AgentId,omitempty"`
	Platform        string `protobuf:"bytes,2,opt,name=Platform,proto3" json:"Platform,omitempty"`
	OperatingSystem string `protobuf:"bytes,3,opt,name=OperatingSystem,proto3" json:"OperatingSystem,omitempty"`
	Architecture    string `protobuf:"bytes,4,opt,name=Architecture,proto3" json:"Architecture,omitempty"`
	Hostname        string `protobuf:"bytes,5,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shellService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shellService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_pb_shellService_proto_rawDescGZIP(), []int{0}
}

func (x *ShellRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ShellRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ShellRequest) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *ShellRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *ShellRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ShellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scripts []*ShellScript `protobuf:"bytes,1,rep,name=Scripts,proto3" json:"Scripts,omitempty"`
}

func (x *ShellResponse) Reset() {
	*x = ShellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shellService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResponse) ProtoMessage() {}

func (x *ShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shellService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResponse.ProtoReflect.Descriptor instead.
func (*ShellResponse) Descriptor() ([]byte, []int) {
	return file_pb_shellService_proto_rawDescGZIP(), []int{1}
}

func (x *ShellResponse) GetScripts() []*ShellScript {
	if x != nil {
		return x.Scripts
	}
	return nil
}

type ShellScript struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Script string `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	Args   string `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Type   string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ShellScript) Reset() {
	*x = ShellScript{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shellService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellScript) ProtoMessage() {}

func (x *ShellScript) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shellService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellScript.ProtoReflect.Descriptor instead.
func (*ShellScript) Descriptor() ([]byte, []int) {
	return file_pb_shellService_proto_rawDescGZIP(), []int{2}
}

func (x *ShellScript) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ShellScript) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *ShellScript) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ShellScriptOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId  string `protobuf:"bytes,1,opt,name=AgentId,proto3" json:"AgentId,omitempty"`
	HostName string `protobuf:"bytes,2,opt,name=HostName,proto3" json:"HostName,omitempty"`
	ScriptId string `protobuf:"bytes,3,opt,name=ScriptId,proto3" json:"ScriptId,omitempty"`
	Output   string `protobuf:"bytes,4,opt,name=Output,proto3" json:"Output,omitempty"`
}

func (x *ShellScriptOutput) Reset() {
	*x = ShellScriptOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shellService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellScriptOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellScriptOutput) ProtoMessage() {}

func (x *ShellScriptOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shellService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellScriptOutput.ProtoReflect.Descriptor instead.
func (*ShellScriptOutput) Descriptor() ([]byte, []int) {
	return file_pb_shellService_proto_rawDescGZIP(), []int{3}
}

func (x *ShellScriptOutput) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ShellScriptOutput) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *ShellScriptOutput) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *ShellScriptOutput) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ShellFragmentRquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outputs []*ShellScriptOutput `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (x *ShellFragmentRquest) Reset() {
	*x = ShellFragmentRquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shellService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShellFragmentRquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellFragmentRquest) ProtoMessage() {}

func (x *ShellFragmentRquest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shellService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellFragmentRquest.ProtoReflect.Descriptor instead.
func (*ShellFragmentRquest) Descriptor() ([]byte, []int) {
	return file_pb_shellService_proto_rawDescGZIP(), []int{4}
}

func (x *ShellFragmentRquest) GetOutputs() []*ShellScriptOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type FragmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Awknowledgement int32 `protobuf:"varint,1,opt,name=Awknowledgement,proto3" json:"Awknowledgement,omitempty"`
}

func (x *FragmentResponse) Reset() {
	*x = FragmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shellService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FragmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentResponse) ProtoMessage() {}

func (x *FragmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shellService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentResponse.ProtoReflect.Descriptor instead.
func (*FragmentResponse) Descriptor() ([]byte, []int) {
	return file_pb_shellService_proto_rawDescGZIP(), []int{5}
}

func (x *FragmentResponse) GetAwknowledgement() int32 {
	if x != nil {
		return x.Awknowledgement
	}
	return 0
}

var File_pb_shellService_proto protoreflect.FileDescriptor

var file_pb_shellService_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x62, 0x2f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x0c, 0x53, 0x68, 0x65, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x28,
	0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x68, 0x65, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x53, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x68, 0x65,
	0x6c, 0x6c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x07, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x73, 0x22, 0x4d, 0x0a, 0x0b, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x7d, 0x0a, 0x11, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22,
	0x43, 0x0a, 0x13, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x07, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x77, 0x6b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x41, 0x77, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x32, 0x78, 0x0a, 0x0c, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73,
	0x12, 0x0d, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x39, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x67, 0x6e, 0x33,
	0x35, 0x68, 0x37, 0x2f, 0x67, 0x6f, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_shellService_proto_rawDescOnce sync.Once
	file_pb_shellService_proto_rawDescData = file_pb_shellService_proto_rawDesc
)

func file_pb_shellService_proto_rawDescGZIP() []byte {
	file_pb_shellService_proto_rawDescOnce.Do(func() {
		file_pb_shellService_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_shellService_proto_rawDescData)
	})
	return file_pb_shellService_proto_rawDescData
}

var file_pb_shellService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_shellService_proto_goTypes = []interface{}{
	(*ShellRequest)(nil),        // 0: ShellRequest
	(*ShellResponse)(nil),       // 1: ShellResponse
	(*ShellScript)(nil),         // 2: ShellScript
	(*ShellScriptOutput)(nil),   // 3: ShellScriptOutput
	(*ShellFragmentRquest)(nil), // 4: ShellFragmentRquest
	(*FragmentResponse)(nil),    // 5: FragmentResponse
}
var file_pb_shellService_proto_depIdxs = []int32{
	2, // 0: ShellResponse.Scripts:type_name -> ShellScript
	3, // 1: ShellFragmentRquest.outputs:type_name -> ShellScriptOutput
	0, // 2: ShellService.GetScripts:input_type -> ShellRequest
	4, // 3: ShellService.SendFragment:input_type -> ShellFragmentRquest
	1, // 4: ShellService.GetScripts:output_type -> ShellResponse
	5, // 5: ShellService.SendFragment:output_type -> FragmentResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_shellService_proto_init() }
func file_pb_shellService_proto_init() {
	if File_pb_shellService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_shellService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shellService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shellService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellScript); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shellService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellScriptOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shellService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShellFragmentRquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shellService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FragmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_shellService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_shellService_proto_goTypes,
		DependencyIndexes: file_pb_shellService_proto_depIdxs,
		MessageInfos:      file_pb_shellService_proto_msgTypes,
	}.Build()
	File_pb_shellService_proto = out.File
	file_pb_shellService_proto_rawDesc = nil
	file_pb_shellService_proto_goTypes = nil
	file_pb_shellService_proto_depIdxs = nil
}
